import { id, type Db } from '../db.js';
import { canonicalLinkedInProfileUrl, parseLeadCsv, scrubLeadNamePart, type LeadFieldMapping, type NormalizedLeadImportRow } from './lead-import.js';

export interface ManagedContact{id:string;firstName:string|null;lastName:string|null;company:string|null;email:string|null;phone:string|null;country:string|null;linkedinUrl:string|null;identityKey:string|null;sourceType:string;sourceId:string|null;raw:Record<string,unknown>}
export interface LeadListSummary{id:string;name:string;sourceType:string;sourceRef:string|null;count:number;createdAt:string}
function normalize(value:string){return value.normalize('NFKC').trim().toLocaleLowerCase('en-US').replace(/\s+/g,' ')}
export function contactIdentityKey(contact:Pick<NormalizedLeadImportRow,'firstName'|'lastName'|'company'|'email'|'linkedinUrl'>){if(contact.linkedinUrl)return`linkedin:${contact.linkedinUrl.toLocaleLowerCase('en-US')}`;if(contact.email)return`email:${contact.email.toLocaleLowerCase('en-US')}`;return`person:${normalize(contact.firstName)}|${normalize(contact.lastName)}|${normalize(contact.company)}`}
function fromRow(row:Record<string,unknown>):ManagedContact{return{id:String(row.id),firstName:row.first_name===null?null:String(row.first_name),lastName:row.last_name===null?null:String(row.last_name),company:row.company===null?null:String(row.company),email:row.email===null?null:String(row.email),phone:row.phone===null?null:String(row.phone),country:row.country===null?null:String(row.country),linkedinUrl:row.linkedin_url===null?null:String(row.linkedin_url),identityKey:row.identity_key===null?null:String(row.identity_key),sourceType:String(row.source_type),sourceId:row.source_id===null?null:String(row.source_id),raw:typeof row.raw_data==='object'&&row.raw_data!==null?row.raw_data as Record<string,unknown>:{}}}

async function upsertContact(db:Db,workspaceId:string,row:NormalizedLeadImportRow,sourceId:string,now:Date){const identity=contactIdentityKey(row);const current=await db.prepare('SELECT id FROM linkedin_contacts WHERE workspace_id=? AND identity_key=?').get<{id:string}>(workspaceId,identity);if(current){await db.prepare(`UPDATE linkedin_contacts SET first_name=?,last_name=?,company=?,email=?,phone=?,country=?,linkedin_url=?,source_type='csv',source_id=?,raw_data=?::jsonb,updated_at=? WHERE workspace_id=? AND id=?`).run(row.firstName,row.lastName,row.company,row.email,row.phone,row.country,row.linkedinUrl,sourceId,JSON.stringify(row.raw),now.toISOString(),workspaceId,current.id);return current.id}const contactId=id('lcontact');await db.prepare(`INSERT INTO linkedin_contacts(id,workspace_id,first_name,last_name,company,email,phone,country,linkedin_url,identity_key,source_type,source_id,raw_data,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?, 'csv',?,?::jsonb,?,?)`).run(contactId,workspaceId,row.firstName,row.lastName,row.company,row.email,row.phone,row.country,row.linkedinUrl,identity,sourceId,JSON.stringify(row.raw),now.toISOString(),now.toISOString());return contactId}

export function previewLeadCsv(csv:Buffer|string,mapping?:LeadFieldMapping){return parseLeadCsv(csv,mapping)}
export async function importLeadList(db:Db,input:{workspaceId:string;name:string;filename:string;csv:Buffer|string;mapping?:LeadFieldMapping},now:Date){const parsed=parseLeadCsv(input.csv,input.mapping);if(!input.name.trim())throw new Error('A lead list needs a name.');const listId=id('llist');const importId=id('limp');let duplicates=0;await db.transaction(async tx=>{await tx.prepare(`INSERT INTO linkedin_lead_lists(id,workspace_id,name,source_type,source_ref,created_at,updated_at) VALUES(?,?,?,'csv',?,?,?)`).run(listId,input.workspaceId,input.name.trim(),input.filename,now.toISOString(),now.toISOString());for(const row of parsed.rows){const contactId=await upsertContact(tx,input.workspaceId,row,importId,now);const inserted=await tx.prepare(`INSERT INTO linkedin_lead_list_members(workspace_id,list_id,contact_id,created_at) VALUES(?,?,?,?) ON CONFLICT DO NOTHING RETURNING contact_id`).get<{contact_id:string}>(input.workspaceId,listId,contactId,now.toISOString());if(!inserted)duplicates+=1}await tx.prepare(`INSERT INTO linkedin_imports(id,workspace_id,list_id,filename,mapping_json,row_count,imported_count,rejected_count,created_at) VALUES(?,?,?,?,?::jsonb,?,?,?,?)`).run(importId,input.workspaceId,listId,input.filename,JSON.stringify(parsed.mapping),parsed.totalRows,parsed.rows.length-duplicates,parsed.errors.length,now.toISOString())});return{list:(await getLeadList(db,input.workspaceId,listId))!,imported:parsed.rows.length-duplicates,rejected:parsed.errors.length,duplicates,errors:parsed.errors}}

export async function listLeadLists(db:Db,workspaceId:string):Promise<LeadListSummary[]>{const rows=await db.prepare(`SELECT l.id,l.name,l.source_type,l.source_ref,TO_CHAR(l.created_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS created_at,COUNT(m.contact_id)::int AS count FROM linkedin_lead_lists l LEFT JOIN linkedin_lead_list_members m ON m.list_id=l.id WHERE l.workspace_id=? GROUP BY l.id ORDER BY l.created_at DESC`).all<Record<string,unknown>>(workspaceId);return rows.map(row=>({id:String(row.id),name:String(row.name),sourceType:String(row.source_type),sourceRef:row.source_ref===null?null:String(row.source_ref),count:Number(row.count),createdAt:String(row.created_at)}))}
export async function getLeadList(db:Db,workspaceId:string,listId:string){return(await listLeadLists(db,workspaceId)).find(item=>item.id===listId)??null}
export async function listLeadListContacts(db:Db,workspaceId:string,listId:string,limit=5000):Promise<ManagedContact[]>{const rows=await db.prepare(`SELECT c.* FROM linkedin_contacts c JOIN linkedin_lead_list_members m ON m.contact_id=c.id WHERE m.workspace_id=? AND m.list_id=? ORDER BY m.created_at ASC LIMIT ?`).all<Record<string,unknown>>(workspaceId,listId,Math.max(1,Math.min(5000,Math.trunc(limit))));return rows.map(fromRow)}
export async function getContact(db:Db,workspaceId:string,contactId:string){const row=await db.prepare('SELECT * FROM linkedin_contacts WHERE workspace_id=? AND id=?').get<Record<string,unknown>>(workspaceId,contactId);return row?fromRow(row):null}
export async function updateContact(db:Db,workspaceId:string,contactId:string,patch:Partial<Pick<ManagedContact,'firstName'|'lastName'|'company'|'email'|'phone'|'country'|'linkedinUrl'>>,now:Date){
 const current=await getContact(db,workspaceId,contactId);if(!current)return null;const next={...current,...patch};
 const firstName=scrubLeadNamePart(next.firstName??'');const lastName=scrubLeadNamePart(next.lastName??'');const company=next.company?.normalize('NFKC').trim()??'';
 if(!firstName||!lastName||!company)throw new Error('First name, last name and company are required after normalization.');
 const emailRaw=next.email?.normalize('NFKC').trim().toLocaleLowerCase('en-US')||null;if(emailRaw&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailRaw))throw new Error('Email is not in a valid address format.');
 const linkedinRaw=next.linkedinUrl?.normalize('NFKC').trim()||null;const linkedinUrl=canonicalLinkedInProfileUrl(linkedinRaw);if(linkedinRaw&&!linkedinUrl)throw new Error('LinkedIn URL must be a linkedin.com/in/... profile URL.');
 const normalized={firstName,lastName,company,email:emailRaw,linkedinUrl};const identity=contactIdentityKey(normalized as NormalizedLeadImportRow);
 const row=await db.prepare(`UPDATE linkedin_contacts SET first_name=?,last_name=?,company=?,email=?,phone=?,country=?,linkedin_url=?,identity_key=?,updated_at=? WHERE workspace_id=? AND id=? RETURNING *`).get<Record<string,unknown>>(firstName,lastName,company,emailRaw,next.phone?.normalize('NFKC').trim()||null,next.country?.normalize('NFKC').trim()||null,linkedinUrl,identity,now.toISOString(),workspaceId,contactId);return row?fromRow(row):null
}
