import { id, type Db } from '../db.js';
import { filterExcluded } from './exclusions.js';
import { getLeadList, listLeadListContacts } from './contact-lists.js';
import { getSeat } from './seats.js';
import { getWorkflow } from './workflow-store.js';

export type ManagedCampaignState='draft'|'running'|'paused'|'stopped'|'completed';
export type ManagedMemberState='pending'|'active'|'waiting'|'waiting_for_connection'|'waiting_for_manual_message'|'paused'|'replied'|'completed'|'removed'|'failed';
export interface ManagedCampaignCreation{campaignId:string;enrolled:number;alreadyActive:number;excluded:number;ineligible:Array<{contactId:string;reason:string}>}
function needsTarget(steps:Array<{kind:string}>){return steps.some(step=>step.kind!=='manual_message')}

const EXECUTION_NOT_WIRED = 'Managed workflow execution is not available yet. The campaign may be saved as a draft, but Trevra will not mark it running until progression is wired into the existing approved LinkedIn worker.';

export async function createManagedCampaign(db:Db,input:{workspaceId:string;name:string;seatKey:string;listId:string;workflowId:string;start?:boolean},now:Date):Promise<ManagedCampaignCreation>{
 if(input.start)throw new Error(EXECUTION_NOT_WIRED);
 const [seat,list,workflow,contacts]=await Promise.all([getSeat(db,input.workspaceId,input.seatKey),getLeadList(db,input.workspaceId,input.listId),getWorkflow(db,input.workspaceId,input.workflowId),listLeadListContacts(db,input.workspaceId,input.listId)]);
 if(!seat)throw new Error('The selected LinkedIn account does not exist.');if(!list)throw new Error('The selected lead list does not exist.');if(!workflow)throw new Error('The selected workflow does not exist.');if(!input.name.trim())throw new Error('A campaign needs a name.');
 const targetRequired=needsTarget(workflow.definition.steps);const ineligible:Array<{contactId:string;reason:string}>=[];
 const candidates=contacts.filter(contact=>{if(!contact.firstName?.trim()||!contact.lastName?.trim()||!contact.company?.trim()||!contact.identityKey){ineligible.push({contactId:contact.id,reason:'First name, last name and company are required.'});return false}if(targetRequired&&!contact.linkedinUrl){ineligible.push({contactId:contact.id,reason:'This workflow needs a LinkedIn profile URL.'});return false}return true});
 const urls=candidates.flatMap(contact=>contact.linkedinUrl?[contact.linkedinUrl]:[]);const exclusion=await filterExcluded(db,input.workspaceId,urls);const excluded=new Set(exclusion.excluded.map(item=>item.targetRef.toLocaleLowerCase('en-US')));const eligible=candidates.filter(contact=>!contact.linkedinUrl||!excluded.has(contact.linkedinUrl.toLocaleLowerCase('en-US')));
 const campaignId=id('lcamp');let enrolled=0;let alreadyActive=0;
 await db.transaction(async tx=>{await tx.prepare(`INSERT INTO linkedin_campaigns(id,workspace_id,name,status,sequence_json,seat_key,workflow_id,lead_list_id,started_at,created_at,updated_at) VALUES(?,?,?,'draft',?::jsonb,?,?,?,NULL,?,?)`).run(campaignId,input.workspaceId,input.name.trim(),JSON.stringify({managerVersion:1,workflowId:workflow.id,steps:workflow.definition.steps}),input.seatKey,workflow.id,list.id,now.toISOString(),now.toISOString());for(const contact of eligible){const member=await tx.prepare(`INSERT INTO linkedin_campaign_members(id,workspace_id,campaign_id,contact_id,identity_key,seat_key,state,current_step,earliest_execution_at,created_at,updated_at) VALUES(?,?,?,?,?,?,'pending',0,NULL,?,?) ON CONFLICT DO NOTHING RETURNING id`).get<{id:string}>(id('lmember'),input.workspaceId,campaignId,contact.id,contact.identityKey,input.seatKey,now.toISOString(),now.toISOString());if(member)enrolled+=1;else alreadyActive+=1}});
 return{campaignId,enrolled,alreadyActive,excluded:excluded.size,ineligible};
}

export async function setManagedCampaignState(db:Db,workspaceId:string,campaignId:string,state:'running'|'paused'|'stopped',now:Date):Promise<boolean>{
 if(state==='running')throw new Error(EXECUTION_NOT_WIRED);
 if(state==='paused'){const result=await db.prepare(`UPDATE linkedin_campaigns SET status='paused',paused_at=?,updated_at=? WHERE workspace_id=? AND id=? AND status='running'`).run(now.toISOString(),now.toISOString(),workspaceId,campaignId);await db.prepare(`UPDATE linkedin_campaign_members SET state='paused',paused_at=?,updated_at=? WHERE workspace_id=? AND campaign_id=? AND state IN ('active','waiting','waiting_for_connection')`).run(now.toISOString(),now.toISOString(),workspaceId,campaignId);return result.changes>0}
 const result=await db.prepare(`UPDATE linkedin_campaigns SET status='stopped',stop_requested_at=COALESCE(stop_requested_at,?),updated_at=? WHERE workspace_id=? AND id=? AND status<>'stopped'`).run(now.toISOString(),now.toISOString(),workspaceId,campaignId);await db.prepare(`UPDATE linkedin_campaign_members SET state='removed',completed_at=?,updated_at=? WHERE workspace_id=? AND campaign_id=? AND state IN ('pending','active','waiting','waiting_for_connection','waiting_for_manual_message','paused')`).run(now.toISOString(),now.toISOString(),workspaceId,campaignId);await db.prepare(`UPDATE linkedin_manual_tasks SET status='cancelled',updated_at=? WHERE workspace_id=? AND campaign_id=? AND status='pending'`).run(now.toISOString(),workspaceId,campaignId);return result.changes>0;
}
export async function setCampaignMemberState(db:Db,workspaceId:string,memberId:string,action:'pause'|'resume'|'remove',now:Date):Promise<boolean>{const state:ManagedMemberState=action==='pause'?'paused':action==='resume'?'active':'removed';const result=await db.prepare(`UPDATE linkedin_campaign_members SET state=?,paused_at=?,completed_at=?,updated_at=? WHERE workspace_id=? AND id=?`).run(state,action==='pause'?now.toISOString():null,action==='remove'?now.toISOString():null,now.toISOString(),workspaceId,memberId);if(action==='remove')await db.prepare(`UPDATE linkedin_manual_tasks SET status='cancelled',updated_at=? WHERE workspace_id=? AND campaign_member_id=? AND status='pending'`).run(now.toISOString(),workspaceId,memberId);return result.changes>0}
export async function listCampaignMembers(db:Db,workspaceId:string,campaignId:string){return db.prepare(`SELECT m.*,c.first_name,c.last_name,c.company,c.linkedin_url,c.email FROM linkedin_campaign_members m JOIN linkedin_contacts c ON c.id=m.contact_id WHERE m.workspace_id=? AND m.campaign_id=? ORDER BY m.created_at ASC`).all<Record<string,unknown>>(workspaceId,campaignId)}
