import type { Db } from '../db.js';

export async function getManagerAnalytics(db:Db,workspaceId:string,filters:{seatKey?:string;campaignId?:string;days?:number}={}){
 const days=Math.max(1,Math.min(365,Math.trunc(filters.days??30)));const since=new Date(Date.now()-days*86_400_000).toISOString();
 const rows=await db.prepare(`SELECT a.kind,a.status,a.target_ref,attr.variant_id FROM linkedin_actions a LEFT JOIN linkedin_action_attribution attr ON attr.action_id=a.id WHERE a.workspace_id=? AND a.recorded_at>=? AND (?::text IS NULL OR a.seat_key=?) AND (?::text IS NULL OR a.campaign_id=?)`).all<{kind:string;status:string;target_ref:string|null;variant_id:string|null}>(workspaceId,since,filters.seatKey??null,filters.seatKey??null,filters.campaignId??null,filters.campaignId??null);
 const delivered=(status:string)=>!['planned','skipped','exported'].includes(status);const invites=rows.filter(row=>row.kind==='invite'&&delivered(row.status));const messages=rows.filter(row=>(row.kind==='dm'||row.kind==='reply')&&delivered(row.status));const accepted=invites.filter(row=>row.status==='accepted'||row.status==='replied');const repliedTargets=new Set(rows.filter(row=>row.status==='replied'&&row.target_ref).map(row=>row.target_ref as string));const messagedTargets=new Set(messages.flatMap(row=>row.target_ref?[row.target_ref]:[]));
 const variants=new Map<string,{sent:number;replyTargets:Set<string>}>();for(const row of messages){if(!row.variant_id)continue;const value=variants.get(row.variant_id)??{sent:0,replyTargets:new Set<string>()};value.sent+=1;if(row.target_ref&&repliedTargets.has(row.target_ref))value.replyTargets.add(row.target_ref);variants.set(row.variant_id,value)}
 return{periodDays:days,invitesSent:invites.length,messagesSent:messages.length,profileViews:rows.filter(row=>row.kind==='profile_view'&&delivered(row.status)).length,follows:rows.filter(row=>row.kind==='follow'&&delivered(row.status)).length,invitesAccepted:accepted.length,acceptanceRate:invites.length===0?null:accepted.length/invites.length,uniqueReplyingLeads:repliedTargets.size,replyRate:messagedTargets.size===0?null:[...messagedTargets].filter(target=>repliedTargets.has(target)).length/messagedTargets.size,variants:[...variants.entries()].map(([variantId,value])=>({variantId,sent:value.sent,replies:value.replyTargets.size,replyRate:value.sent===0?null:value.replyTargets.size/value.sent}))};
}
