import type { Express, NextFunction, Request, Response } from 'express';
import multer from 'multer';
import { z } from 'zod';
import type { Db } from '../db.js';
import { importLeadList, listLeadListContacts, listLeadLists, previewLeadCsv, updateContact } from './contact-lists.js';
import { createManagedCampaign, listCampaignMembers, setCampaignMemberState, setManagedCampaignState } from './managed-campaigns.js';
import { getManagerAnalytics } from './manager-analytics.js';
import { listSeats, upsertSeat } from './seats.js';
import { createWorkflow, listWorkflows, updateWorkflow } from './workflow-store.js';

interface AuthedRequest extends Request{auth?:{workspaceId:string;userId?:string}}
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:1}});
function route(fn:(req:AuthedRequest,res:Response)=>Promise<void>){return(req:AuthedRequest,res:Response,next:NextFunction)=>{void fn(req,res).catch((error)=>{const message=error instanceof Error?error.message:'Request failed';if(message.includes('duplicate key')||message.includes('unique constraint'))return res.status(409).json({error:message});if(error instanceof z.ZodError)return res.status(400).json({error:'Invalid request',issues:error.issues});if(message.includes('required')||message.includes('must')||message.includes('does not exist')||message.includes('needs'))return res.status(400).json({error:message});next(error)})}}
function workspace(req:AuthedRequest){if(!req.auth?.workspaceId)throw new Error('Session expired');return req.auth.workspaceId}
const mappingSchema=z.record(z.string()).optional();

export function registerLinkedInManagerRoutes(app:Express,db:Db):void{
 app.get('/api/linkedin/manager/accounts',route(async(req,res)=>{res.json({accounts:await listSeats(db,workspace(req))})}));
 app.post('/api/linkedin/manager/accounts',route(async(req,res)=>{const body=z.object({seatKey:z.string().min(1).max(64),label:z.string().min(1).max(120),timezone:z.string().min(1),profileUrl:z.string().url().nullish()}).parse(req.body);const account=await upsertSeat(db,workspace(req),{label:body.label,timezone:body.timezone,profileUrl:body.profileUrl??null},new Date(),body.seatKey);res.status(201).json({account})}));
 app.patch('/api/linkedin/manager/accounts/:seatKey',route(async(req,res)=>{const body=z.object({label:z.string().min(1).max(120).optional(),timezone:z.string().min(1).optional(),workingDays:z.array(z.number().int().min(0).max(6)).min(1).optional(),workingStart:z.string().optional(),workingEnd:z.string().optional(),operatorLimits:z.object({invite:z.number().int().optional(),message:z.number().int().optional(),profile_view:z.number().int().optional(),follow:z.number().int().optional()}).optional()}).parse(req.body);const account=await upsertSeat(db,workspace(req),body,new Date(),req.params.seatKey);res.json({account})}));

 app.post('/api/linkedin/manager/lists/preview',upload.single('file'),route(async(req,res)=>{if(!req.file)throw new Error('A CSV file is required.');const mapping=req.body.mapping?mappingSchema.parse(JSON.parse(String(req.body.mapping))):undefined;res.json(previewLeadCsv(req.file.buffer,mapping))}));
 app.post('/api/linkedin/manager/lists/import',upload.single('file'),route(async(req,res)=>{if(!req.file)throw new Error('A CSV file is required.');const name=String(req.body.name??'').trim();if(!name)throw new Error('A lead list name is required.');const mapping=req.body.mapping?mappingSchema.parse(JSON.parse(String(req.body.mapping))):undefined;const result=await importLeadList(db,{workspaceId:workspace(req),name,filename:req.file.originalname||'import.csv',csv:req.file.buffer,mapping},new Date());res.status(201).json(result)}));
 app.get('/api/linkedin/manager/lists',route(async(req,res)=>{res.json({lists:await listLeadLists(db,workspace(req))})}));
 app.get('/api/linkedin/manager/lists/:listId/contacts',route(async(req,res)=>{res.json({contacts:await listLeadListContacts(db,workspace(req),req.params.listId,Number(req.query.limit??5000))})}));
 app.patch('/api/linkedin/manager/contacts/:contactId',route(async(req,res)=>{const body=z.object({firstName:z.string().optional(),lastName:z.string().optional(),company:z.string().optional(),email:z.string().email().nullish(),phone:z.string().nullish(),country:z.string().nullish(),linkedinUrl:z.string().url().nullish()}).parse(req.body);const contact=await updateContact(db,workspace(req),req.params.contactId,body,new Date());if(!contact){res.status(404).json({error:'Contact not found'});return}res.json({contact})}));

 app.get('/api/linkedin/manager/workflows',route(async(req,res)=>{res.json({workflows:await listWorkflows(db,workspace(req))})}));
 app.post('/api/linkedin/manager/workflows',route(async(req,res)=>{const body=z.object({name:z.string().min(1).max(160),definition:z.unknown()}).parse(req.body);const workflow=await createWorkflow(db,workspace(req),body.name,body.definition,new Date());res.status(201).json({workflow})}));
 app.patch('/api/linkedin/manager/workflows/:workflowId',route(async(req,res)=>{const body=z.object({name:z.string().min(1).max(160).optional(),definition:z.unknown().optional(),status:z.enum(['active','archived']).optional()}).parse(req.body);const workflow=await updateWorkflow(db,workspace(req),req.params.workflowId,body,new Date());if(!workflow){res.status(404).json({error:'Workflow not found'});return}res.json({workflow})}));

 app.post('/api/linkedin/manager/campaigns',route(async(req,res)=>{const body=z.object({name:z.string().min(1).max(160),seatKey:z.string().min(1).max(64),listId:z.string().min(1),workflowId:z.string().min(1),start:z.boolean().optional()}).parse(req.body);res.status(201).json(await createManagedCampaign(db,{workspaceId:workspace(req),...body},new Date()))}));
 app.post('/api/linkedin/manager/campaigns/:campaignId/state',route(async(req,res)=>{const body=z.object({state:z.enum(['running','paused','stopped'])}).parse(req.body);const changed=await setManagedCampaignState(db,workspace(req),req.params.campaignId,body.state,new Date());if(!changed){res.status(404).json({error:'Campaign not found or state transition not allowed'});return}res.json({ok:true,state:body.state})}));
 app.get('/api/linkedin/manager/campaigns/:campaignId/members',route(async(req,res)=>{res.json({members:await listCampaignMembers(db,workspace(req),req.params.campaignId)})}));
 app.post('/api/linkedin/manager/members/:memberId/state',route(async(req,res)=>{const body=z.object({action:z.enum(['pause','resume','remove'])}).parse(req.body);const changed=await setCampaignMemberState(db,workspace(req),req.params.memberId,body.action,new Date());if(!changed){res.status(404).json({error:'Campaign member not found'});return}res.json({ok:true})}));

 app.get('/api/linkedin/manager/tasks',route(async(req,res)=>{const rows=await db.prepare(`SELECT t.*,c.first_name,c.last_name,c.company,c.linkedin_url,cam.name AS campaign_name FROM linkedin_manual_tasks t JOIN linkedin_contacts c ON c.id=t.contact_id JOIN linkedin_campaigns cam ON cam.id=t.campaign_id WHERE t.workspace_id=? AND (?::text IS NULL OR t.seat_key=?) AND (?::text IS NULL OR t.campaign_id=?) AND (?::text IS NULL OR t.status=?) ORDER BY CASE WHEN t.status='pending' THEN 0 ELSE 1 END,t.created_at ASC`).all<Record<string,unknown>>(workspace(req),req.query.seatKey??null,req.query.seatKey??null,req.query.campaignId??null,req.query.campaignId??null,req.query.status??null,req.query.status??null);res.json({tasks:rows})}));
 app.post('/api/linkedin/manager/tasks/:taskId/complete',route(async(req,res)=>{const now=new Date().toISOString();const task=await db.transaction(async tx=>{const row=await tx.prepare(`UPDATE linkedin_manual_tasks SET status='completed',completed_at=?,updated_at=? WHERE workspace_id=? AND id=? AND status='pending' RETURNING campaign_member_id`).get<{campaign_member_id:string}>(now,now,workspace(req),req.params.taskId);if(row)await tx.prepare(`UPDATE linkedin_campaign_members SET state='active',current_step=current_step+1,earliest_execution_at=?,updated_at=? WHERE workspace_id=? AND id=?`).run(now,now,workspace(req),row.campaign_member_id);return row});if(!task){res.status(404).json({error:'Pending task not found'});return}res.json({ok:true})}));

 app.get('/api/linkedin/manager/analytics',route(async(req,res)=>{res.json(await getManagerAnalytics(db,workspace(req),{seatKey:typeof req.query.seatKey==='string'?req.query.seatKey:undefined,campaignId:typeof req.query.campaignId==='string'?req.query.campaignId:undefined,days:req.query.days?Number(req.query.days):undefined}))}));
}
