import { id, type Db } from '../db.js';
import { outreachWorkflowSchema, type OutreachWorkflow } from './workflow-types.js';

export interface StoredOutreachWorkflow{id:string;name:string;status:string;definition:OutreachWorkflow;createdAt:string;updatedAt:string}
const SELECT=`id,name,status,definition_json,TO_CHAR(created_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS created_at,TO_CHAR(updated_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS updated_at`;
function fromRow(row:Record<string,unknown>):StoredOutreachWorkflow{return{id:String(row.id),name:String(row.name),status:String(row.status),definition:outreachWorkflowSchema.parse(row.definition_json),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}}

export async function createWorkflow(db:Db,workspaceId:string,name:string,definition:unknown,now:Date):Promise<StoredOutreachWorkflow>{const parsed=outreachWorkflowSchema.parse(definition);const row=await db.prepare(`INSERT INTO linkedin_workflows(id,workspace_id,name,status,definition_json,created_at,updated_at) VALUES(?,?,?,'active',?::jsonb,?,?) RETURNING ${SELECT}`).get<Record<string,unknown>>(id('lwf'),workspaceId,name.trim(),JSON.stringify(parsed),now.toISOString(),now.toISOString());if(!row)throw new Error('Workflow could not be created.');return fromRow(row)}
export async function getWorkflow(db:Db,workspaceId:string,workflowId:string):Promise<StoredOutreachWorkflow|null>{const row=await db.prepare(`SELECT ${SELECT} FROM linkedin_workflows WHERE workspace_id=? AND id=?`).get<Record<string,unknown>>(workspaceId,workflowId);return row?fromRow(row):null}
export async function listWorkflows(db:Db,workspaceId:string):Promise<StoredOutreachWorkflow[]>{return(await db.prepare(`SELECT ${SELECT} FROM linkedin_workflows WHERE workspace_id=? AND status<>'archived' ORDER BY updated_at DESC`).all<Record<string,unknown>>(workspaceId)).map(fromRow)}
export async function updateWorkflow(db:Db,workspaceId:string,workflowId:string,input:{name?:string;definition?:unknown;status?:'active'|'archived'},now:Date):Promise<StoredOutreachWorkflow|null>{const current=await getWorkflow(db,workspaceId,workflowId);if(!current)return null;const definition=input.definition===undefined?current.definition:outreachWorkflowSchema.parse(input.definition);const row=await db.prepare(`UPDATE linkedin_workflows SET name=?,definition_json=?::jsonb,status=?,updated_at=? WHERE workspace_id=? AND id=? RETURNING ${SELECT}`).get<Record<string,unknown>>(input.name?.trim()||current.name,JSON.stringify(definition),input.status??current.status,now.toISOString(),workspaceId,workflowId);return row?fromRow(row):null}
