#!/usr/bin/env bash
# Generates the random secrets .env.oracle needs and prints them ready to paste.
# Values are printed to stdout only -- nothing is written to disk or logged, so
# redirect deliberately:  ./gen-secrets.sh >> .env.oracle && chmod 600 .env.oracle
set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required" >&2
  exit 1
fi

# 32 bytes of entropy, base64url, no padding -- satisfies both the 32-char
# minimum in config.ts and the URL-safe charset INDEXNOW_KEY is checked against.
secret() { openssl rand -base64 32 | tr '+/' '-_' | tr -d '='; }

# TREVRA_SECRETS_KEY IS NOT GENERATED BY secret() ABOVE, AND THAT IS NOT AN
# OVERSIGHT. Every other value here is compared as a string; this one is
# DECODED. `secrets/crypto.ts` `parseKey` requires standard base64 -- charset
# [A-Za-z0-9+/] with padding -- and must decode to exactly 32 bytes, so the
# base64url that secret() produces (`-_`, padding stripped) would be rejected
# at startup with "must be base64". Hence `openssl rand -base64 32` raw, whose
# 44 characters decode to exactly the 32 bytes AES-256 wants.
#
# WHY IT IS IN THE LIST AT ALL, given it used not to be: without it the box
# comes up with CREDENTIAL CUSTODY SILENTLY OFF. `secretsConfigured()` returns
# false, `/api/agent-setup` reports `available: false`, every BYOK write is
# refused and every LinkedIn or Reddit sign-in refuses to be stored -- and
# nothing about a green deploy says so. A hosted runbook that produces that box
# is a runbook that produces a broken product, so the key is generated with the
# rest and the operator never has to know it was optional.

cat <<EOF
TREVRA_DB_PASSWORD=$(secret)
BETTER_AUTH_SECRET=$(secret)
MARKETING_HASH_SALT=$(secret)
TRACTION_ADMIN_TOKEN=$(secret)
TREVRA_AGENT_TOKEN_PEPPER=$(secret)
INDEXNOW_KEY=$(secret)
TREVRA_SECRETS_KEY=$(openssl rand -base64 32)
EOF

# Nango's encryption key must be exactly 32 bytes of standard base64.
cat <<EOF
# Only needed with the self-hosted Nango overlay:
# NANGO_DB_PASSWORD=$(secret)
# NANGO_ENCRYPTION_KEY=$(openssl rand -base64 32)
EOF

# Deliberately NOT generated: TREVRA_SECRETS_KEY_PREVIOUS is the OUTGOING key
# during a rotation window, so a fresh random value would be meaningless and a
# generated one would invite somebody to paste it in. Set it by hand, to the
# key you are rotating AWAY from, and remove it only once
# `secretsCustodyReport()` reports \`complete\` -- see migration 056.
cat <<EOF
# During a key rotation only, set to the PREVIOUS TREVRA_SECRETS_KEY:
# TREVRA_SECRETS_KEY_PREVIOUS=
EOF
