#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.selfhost"
PORT="${TREVRA_SELFHOST_PORT:-43900}"

if [[ -e "${ENV_FILE}" ]]; then
  printf 'Keeping existing %s\n' "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  exit 0
fi

umask 077
DB_PASSWORD="$(openssl rand -hex 24)"
BETTER_AUTH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
MARKETING_HASH_SALT="$(openssl rand -hex 32)"
TRACTION_ADMIN_TOKEN="$(openssl rand -hex 32)"
AGENT_TOKEN_PEPPER="$(openssl rand -hex 32)"
SECRETS_KEY="$(openssl rand -base64 32 | tr -d '\n')"
INDEXNOW_KEY="$(openssl rand -hex 16)"

cat >"${ENV_FILE}" <<EOF
TREVRA_SELFHOST_PORT=${PORT}
TREVRA_DB_PASSWORD=${DB_PASSWORD}
APP_ORIGIN=http://localhost:${PORT}
BETTER_AUTH_URL=http://localhost:${PORT}
PUBLIC_SITE_URL=http://localhost:${PORT}
COOKIE_SECURE=false
TREVRA_DEPLOYMENT_MODE=local
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
MARKETING_HASH_SALT=${MARKETING_HASH_SALT}
TRACTION_ADMIN_TOKEN=${TRACTION_ADMIN_TOKEN}
TREVRA_AGENT_TOKEN_PEPPER=${AGENT_TOKEN_PEPPER}
TREVRA_SECRETS_KEY=${SECRETS_KEY}
INDEXNOW_KEY=${INDEXNOW_KEY}
PUBLIC_LEGAL_NAME=Trevra
PUBLIC_SUPPORT_EMAIL=support@trevra.local
SECURITY_CONTACT_EMAIL=security@trevra.local
PUBLIC_REGISTRY_API_URL=http://localhost:${PORT}
PUBLIC_REGISTRY_CORS_ORIGIN=http://localhost:${PORT}
TREVRA_ORCHESTRATOR=postgres
ALLOW_DEMO_AUTH=false
ALLOW_SIMULATED_EXECUTION=false
TREVRA_LINKEDIN_LOCAL=false
TREVRA_REDDIT_LOCAL=false
TREVRA_LINKEDIN_LEAD_SOURCING=false
NANGO_API_KEY=
NANGO_WEBHOOK_SIGNING_KEY=
NANGO_HOST=
NANGO_PUBLIC_SERVER_URL=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
OPENAI_API_KEY=
TREVRA_SANDBOX_GATEWAY_URL=
TREVRA_SANDBOX_GATEWAY_TOKEN=
TREVRA_AGENT_CLI_OAUTH_TOKEN=
TREVRA_AGENT_CLI_MODEL=
TREVRA_ALLOW_PRIVATE_MODEL_HOSTS=false
EOF
chmod 600 "${ENV_FILE}"
printf 'Created %s for http://localhost:%s\n' "${ENV_FILE}" "${PORT}"
